In [42]:
import pandas as pd
df = pd.read_csv("flight_delays_train.csv/flight_delays_train.csv")
print(df)
ud = pd.read_csv("flight_delays_test.csv/flight_delays_test.csv")

      Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance  \
0       c-8       c-21       c-7     1934            AA    ATL  DFW       732
1       c-4       c-20       c-3     1548            US    PIT  MCO       834
2       c-9        c-2       c-5     1422            XE    RDU  CLE       416
3      c-11       c-25       c-6     1015            OO    DEN  MEM       872
4      c-10        c-7       c-6     1828            WN    MDW  OMA       423
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-5        c-4       c-3     1618            OO    SFO  RDD       199
99996   c-1       c-18       c-3      804            CO    EWR  DAB       884
99997   c-1       c-24       c-2     1901            NW    DTW  IAH      1076
99998   c-4       c-27       c-4     1515            MQ    DFW  GGG       140
99999  c-11       c-17       c-4     1800            WN    SEA  SMF       605

      dep_delayed_15min
0                     N
1                     N
2                     N
3                     N
4                     Y
...                 ...
99995                 N
99996                 N
99997                 N
99998                 N
99999                 N

[100000 rows x 9 columns]

In [43]:
ud

      Month DayofMonth DayOfWeek  DepTime UniqueCarrier Origin Dest  Distance
0       c-7       c-25       c-3      615            YV    MRY  PHX       598
1       c-4       c-17       c-2      739            WN    LAS  HOU      1235
2      c-12        c-2       c-7      651            MQ    GSP  ORD       577
3       c-3       c-25       c-7     1614            WN    BWI  MHT       377
4       c-6        c-6       c-3     1505            UA    ORD  STL       258
...     ...        ...       ...      ...           ...    ...  ...       ...
99995   c-6        c-5       c-2      852            WN    CRP  HOU       187
99996  c-11       c-24       c-6     1446            UA    ORD  LAS      1515
99997   c-1       c-30       c-2     1509            OO    ORD  SGF       438
99998   c-1        c-5       c-5      804            DL    LGA  ATL       761
99999  c-10       c-29       c-1      834            OO    MKE  MSP       297

[100000 rows x 8 columns]

In [44]:
import numpy as np 
a=np.percentile(df['Distance'],75)
b=np.percentile(df['Distance'],25)
IQRA=a-b
UpperA=(a+1.5*IQRA)
LowerA=(b-1.5*IQRA)
print(UpperA,LowerA)

for i in range(len(df)):
    if (df.at[i,'Distance']>UpperA):
         df.at[i,'Distance']=UpperA  
    elif (df.at[i,'Distance']<LowerA):
        df.at[i,'Distance']=LowerA

1917.0 -643.0

In [45]:
a=np.percentile(ud['Distance'],75)
b=np.percentile(ud['Distance'],25)
IQRA=a-b
UpperA=int((a+1.5*IQRA))
LowerA=int((b-1.5*IQRA))
print(UpperA,LowerA)

for i in range(len(ud)):
    if (ud.at[i,'Distance']>UpperA):
         ud.at[i,'Distance']=UpperA  
    elif (ud.at[i,'Distance']<LowerA):
        ud.at[i,'Distance']=LowerA

1888 -619

In [46]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder(handle_unknown='use_encoded_value', unknown_value=-1)
categorical_columns = ['UniqueCarrier', 'Origin', 'Dest']

df[categorical_columns] = ordinal_encoder.fit_transform(df[categorical_columns])
ud[categorical_columns] = ordinal_encoder.transform(ud[categorical_columns])

In [47]:
from sklearn.preprocessing import MinMaxScaler
x=df.drop(columns=['dep_delayed_15min'])
y=df['dep_delayed_15min']
scaler=MinMaxScaler()
cols=['Month','DayofMonth','DayOfWeek']
for i in range(len(cols)):
    x[cols[i]] = x[cols[i]].str.replace('c-', '').astype(float)
    ud[cols[i]] = ud[cols[i]].str.replace('c-', '').astype(float)
for column in x.columns:
    x[column] = scaler.fit_transform(pd.DataFrame(x[column]))
    ud[column] = scaler.fit_transform(pd.DataFrame(ud[column]))

In [48]:
x

,Month,DayofMonth,DayOfWeek,DepTime,UniqueCarrier,Origin,Dest,Distance
0,0.636364,0.666667,1.000000,0.763127,0.000000,0.062500,0.270833,0.372019
1,0.272727,0.633333,0.333333,0.610738,0.857143,0.753472,0.593750,0.426073
2,0.727273,0.033333,0.666667,0.560995,0.952381,0.791667,0.204861,0.204557
3,0.909091,0.800000,0.833333,0.400316,0.714286,0.270833,0.607639,0.446211
4,0.818182,0.200000,0.833333,0.721279,0.904762,0.604167,0.690972,0.208267
...,...,...,...,...,...,...,...,...
99995,0.363636,0.100000,0.333333,0.638373,0.714286,0.854167,0.777778,0.089560
99996,0.000000,0.566667,0.333333,0.317015,0.190476,0.319444,0.250000,0.452570
99997,0.000000,0.766667,0.166667,0.750099,0.619048,0.295139,0.454861,0.554319
99998,0.272727,0.866667,0.500000,0.597710,0.571429,0.274306,0.371528,0.058294
99999,0.909091,0.533333,0.500000,0.710225,0.904762,0.850694,0.878472,0.304716

In [49]:
ud

,Month,DayofMonth,DayOfWeek,DepTime,UniqueCarrier,Origin,Dest,Distance
0,0.545455,0.800000,0.333333,0.255940,1.000000,0.660900,0.733564,0.305331
1,0.272727,0.533333,0.166667,0.307628,0.909091,0.525952,0.432526,0.648358
2,1.000000,0.033333,1.000000,0.270946,0.590909,0.404844,0.702422,0.294023
3,0.181818,0.800000,1.000000,0.672363,0.909091,0.166090,0.622837,0.186322
4,0.454545,0.166667,0.333333,0.626928,0.818182,0.709343,0.903114,0.122240
...,...,...,...,...,...,...,...,...
99995,0.454545,0.133333,0.166667,0.354731,0.909091,0.238754,0.432526,0.084006
99996,0.909091,0.766667,0.833333,0.602334,0.818182,0.709343,0.522491,0.799138
99997,0.000000,0.966667,0.166667,0.628595,0.727273,0.709343,0.851211,0.219171
99998,0.000000,0.133333,0.666667,0.334723,0.318182,0.550173,0.062284,0.393107
99999,0.818182,0.933333,0.000000,0.347228,0.727273,0.633218,0.667820,0.143242

In [50]:
y

0        N
1        N
2        N
3        N
4        Y
        ..
99995    N
99996    N
99997    N
99998    N
99999    N
Name: dep_delayed_15min, Length: 100000, dtype: object

In [51]:
from sklearn.preprocessing import LabelEncoder
label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

In [52]:
y_encoded

array([0, 0, 0, ..., 0, 0, 0])

In [53]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,stratify=y,random_state=42)

In [54]:
import matplotlib.pyplot as plt
from sklearn.neighbors import KNeighborsClassifier
knn_classifier = KNeighborsClassifier(n_neighbors=3)
# Train the classifier on the training data
knn_classifier.fit(x_train, y_train)
# Make predictions on the test data
y_pred = knn_classifier.predict(x_test)
unlabeled_predictions = knn_classifier.predict(ud)

In [55]:
unlabeled_predictions

array(['N', 'N', 'N', ..., 'N', 'N', 'N'], dtype=object)

In [69]:
# Identify confident predictions (you can adjust the confidence threshold)
confidence_threshold = 0.7
confident_predictions_mask = knn_classifier.predict_proba(ud).max(axis=1) >= confidence_threshold

# Concatenate confident predictions with the original labeled dataset
x_concatenated = pd.concat([x_train,ud[confident_predictions_mask]])
y_concatenated = pd.concat([y_train, pd.Series(unlabeled_predictions[confident_predictions_mask])])

# Split the concatenated dataset into training and validation sets
x_train_split, x_val_split, y_train_split, y_val_split = train_test_split(
    x_concatenated, y_concatenated, test_size=0.2, random_state=42
)

# Create a KNN classifier
knn_classifier_retrain = KNeighborsClassifier(n_neighbors=3)

# Train the classifier on the training set
knn_classifier_retrain.fit(x_train_split, y_train_split)

# Make predictions on the validation set
y_pred_val = knn_classifier_retrain.predict(x_val_split)
# Evaluate the performance on the validation set (you can use any metric you need)
accuracy_val = accuracy_score(y_val_split, y_pred_val)
f1_val = f1_score(y_val_split, y_pred_val, average='weighted')  

# Print the evaluation results
print("Validation Accuracy:", accuracy_val)
print("Validation F1 Score:", f1_val)

Validation Accuracy: 0.8960501206207467
Validation F1 Score: 0.8767150810536681

In [70]:
from sklearn.model_selection import cross_val_score, StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score

# Perform 5-fold cross-validation on the concatenated dataset
stratified_kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
cv_accuracies = []
cv_f1_scores = []

for train_idx, val_idx in stratified_kfold.split(x_concatenated, y_concatenated):
    x_train_fold = x_concatenated.iloc[train_idx]
    y_train_fold = y_concatenated.iloc[train_idx]
    x_val_fold = x_concatenated.iloc[val_idx]
    y_val_fold = y_concatenated.iloc[val_idx]

    # Create and train the classifier for each fold
    knn_classifier_fold = KNeighborsClassifier(n_neighbors=3)
    knn_classifier_fold.fit(x_train_fold, y_train_fold)

    # Make predictions on the validation set
    y_pred_fold = knn_classifier_fold.predict(x_val_fold)

    # Calculate accuracy and F1 score for each fold
    accuracy_fold = accuracy_score(y_val_fold, y_pred_fold)
    f1_fold = f1_score(y_val_fold, y_pred_fold, average='weighted')

    cv_accuracies.append(accuracy_fold)
    cv_f1_scores.append(f1_fold)

# Print the cross-validation results
print("Cross-Validation Accuracies:", cv_accuracies)
print("Mean Accuracy:", np.mean(cv_accuracies))
print("Cross-Validation F1 Scores:", cv_f1_scores)
print("Mean F1 Score:", np.mean(cv_f1_scores))

Cross-Validation Accuracies: [0.8978504302740071, 0.8944658481258777, 0.8961581391999424, 0.8974506697393058, 0.8970545873541697]
Mean Accuracy: 0.8965959349386606
Cross-Validation F1 Scores: [0.8802259487992211, 0.8766048232274384, 0.8771487082623454, 0.8796212521796766, 0.8782737177022739]
Mean F1 Score: 0.878374890034191